name: Generate source build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: setup yq
      run: |
        sudo snap install yq
        sudo apt-get update --fix-missing
        sudo apt-get install -y -f -o Acquire::Retries=3 libfuse2

    - name: configure
      run: ./configure --wget-json-search --yq-go --compile-json-c

    - name: make
      run: |
        sudo chsh -s $(which bash) $(whoami)
        make main.c osc_sdk.c osc_sdk.h oapi-cli-completion.bash
        tar c osc_sdk.c osc_sdk.h main.c oapi-cli-completion.bash > build-src.tar

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "sources build (nightly)"
          files: build-src.tar
